export enum CompOpIGCharacteristics {
    AFFECTED_ENTITY = 'Affected Entity',
    COMPONENT_TYPE = 'Component Type',
    COMPONENT_SUBTYPE = 'Component Subtype',
    OPERATION_CAUSE = 'Operation Cause',
    OPERATION_CERTAINTY = 'Operation Certainty',
    OPERATION_TYPE = 'Operation Type',
    ENTITY_OPERATION_TYPE = 'Entity Operation Type',
    PROPERTY_PATH_BEFORE = 'Previous Property Path',
    PROPERTY_PATH_AFTER = 'Property Path',
    PROPERTY_VALUE_BEFORE = 'Previous Property Value',
    PROPERTY_VALUE_AFTER = 'Property Value',
    DEPENDENCY_RELATIONSHIP_SOURCE_PROPERTY_PATH_BEFORE = "Previous Source Property Path",
    DEPENDENCY_RELATIONSHIP_SOURCE_PROPERTY_PATH_AFTER = "Source Property Path",
    DEPENDENCY_RELATIONSHIP_TARGET_ATTRIBUTE_PATH_BEFORE = "Previous Target Attribute Path",
    DEPENDENCY_RELATIONSHIP_TARGET_ATTRIBUTE_PATH_AFTER = "Target Attribute Path",
}