
name: yarn-publish
on:
  # Release using 'npm version minor'
  create:
    tags:
      - v*
jobs:
  npm-publish:
    name: yarn-publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.17.0
        registry-url: https://registry.npmjs.com/

    - run: yarn ci && yarn build && yarn test

    - run: npx lerna publish from-package --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
